'use strict';
// The real code-generation engine. This is what makes PowerCodex actually build:
// it authors real React + TypeScript screens into the project's src/, wires them into
// the router, and (in real mode) verifies the result with the project's own build.
//
// It is deterministic-first: even with no AI CLI present it emits a working, strict-TS
// screen that implements the approved capabilities against sample data — never theater,
// always a file that compiles. When a provider IS present it is asked to author a richer
// component; the output is validated and only used if it looks like a real default-export
// TSX module, otherwise the deterministic screen is kept. Every result reports whether a
// file was actually written and whether the build verified it.
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

// ---- project layout discovery -------------------------------------------------

// Find the app's source root. Code Apps use src/; we accept a couple of fallbacks.
function findSrc(root) {
  for (const c of ['src', 'app', '.']) {
    const p = path.join(root, c);
    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) {
      if (c === '.' && !fs.existsSync(path.join(p, 'main.tsx')) && !fs.existsSync(path.join(p, 'index.tsx'))) continue;
      return p;
    }
  }
  return path.join(root, 'src');
}

function isCodeApp(root) {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const dd = Object.assign({}, pkg.dependencies, pkg.devDependencies);
    return !!(dd.react || dd.vite || dd['react-dom']);
  } catch {
    return false;
  }
}

// A screen's `name` becomes a filename under src/pages/. It can originate from
// client-supplied intake tasks, so it must never be trusted as a path: strip it
// down to a safe, single-segment slug (no separators, no `..`, no leading dots).
// Returns '' when nothing usable remains, so callers can reject the task.
function safeScreenName(raw) {
  const slug = String(raw == null ? '' : raw)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-') // collapse anything non-alphanumeric to a hyphen
    .replace(/^-+|-+$/g, '') // trim leading/trailing hyphens
    .slice(0, 64);
  return slug;
}

// Defence in depth: confirm the resolved write target stays inside `dir`.
function isWithin(dir, target) {
  const base = path.resolve(dir);
  const resolved = path.resolve(target);
  return resolved === base || resolved.startsWith(base + path.sep);
}

// ---- the deterministic screen generator ---------------------------------------

// Produce a strict-TypeScript React screen implementing the capability flags against
// inline sample data. Only the lines whose flags are on are emitted, so there are no
// unused locals (the starter compiles with strict + noUnusedLocals).
function generateScreen({ componentName, displayName, goal, capabilities = {}, items = [] }) {
  const c = capabilities;
  const L = []; // lines
  const p = (s = '') => L.push(s);

  p(`// Generated by PowerCodex — ${displayName || componentName}`);
  p(`// Goal: ${String(goal || '').replace(/\n/g, ' ').slice(0, 120)}`);
  if (items.length) {
    p('// Approved capabilities:');
    for (const it of items.slice(0, 8)) p('//   • ' + String(it).replace(/<[^>]+>/g, '').replace(/[<>]/g, '').replace(/\n/g, ' ').slice(0, 90));
  }
  p('import { useMemo, useState } from "react"');
  p('');
  p('type Item = {');
  p('  id: number');
  p('  title: string');
  p('  owner: string');
  p('  due: string');
  p('  status: "Open" | "Done"');
  p('}');
  p('');
  if (c.filterByUser) p('const CURRENT_USER = "you"');
  p('const SAMPLE: Item[] = [');
  p('  { id: 1, title: "First item", owner: "you", due: "2026-06-01", status: "Open" },');
  p('  { id: 2, title: "Second item", owner: "alex", due: "2026-06-10", status: "Open" },');
  p('  { id: 3, title: "Third item", owner: "you", due: "2026-05-20", status: "Done" },');
  p('  { id: 4, title: "Fourth item", owner: "you", due: "2026-07-02", status: "Open" },');
  p('  { id: 5, title: "Fifth item", owner: "sam", due: "2026-06-18", status: "Open" },');
  p(']');
  p('');
  if (c.highlight) {
    p('function isOverdue(item: Item): boolean {');
    p('  return item.status !== "Done" && new Date(item.due).getTime() < Date.now()');
    p('}');
    p('');
  }
  p(`export default function ${componentName}() {`);
  p('  const [items, setItems] = useState<Item[]>(SAMPLE)');
  p('  const [query, setQuery] = useState("")');
  p('');
  p('  const visible = useMemo(() => {');
  p('    let rows = items');
  if (c.filterByUser) p('    rows = rows.filter((r) => r.owner === CURRENT_USER)');
  p('    if (query.trim()) {');
  p('      const q = query.toLowerCase()');
  p('      rows = rows.filter((r) => r.title.toLowerCase().includes(q))');
  p('    }');
  p('    rows = [...rows].sort((a, b) => a.due.localeCompare(b.due))');
  p('    return rows');
  p('  }, [items, query])');
  p('');
  if (c.rowAction) {
    p('  function toggle(id: number) {');
    p('    setItems((prev) =>');
    p('      prev.map((r) => (r.id === id ? { ...r, status: r.status === "Done" ? "Open" : "Done" } : r)),');
    p('    )');
    p('  }');
    p('');
  }
  // JSX
  p('  return (');
  p('    <div className="p-6 max-w-3xl mx-auto">');
  p(`      <h1 className="text-2xl font-semibold mb-1">${esc(displayName || componentName)}</h1>`);
  p(`      <p className="text-sm text-muted-foreground mb-4">${esc(oneLine(goal) || 'Your screen')}</p>`);
  p('      <input');
  p('        value={query}');
  p('        onChange={(e) => setQuery(e.target.value)}');
  p('        placeholder="Search…"');
  p('        className="w-full mb-4 rounded-md border px-3 py-2 text-sm"');
  p('      />');
  p('      <table className="w-full text-sm border-collapse">');
  p('        <thead>');
  p('          <tr className="text-left border-b">');
  p('            <th className="py-2 pr-4">Title</th>');
  p('            <th className="py-2 pr-4">Owner</th>');
  p('            <th className="py-2 pr-4">Due</th>');
  p('            <th className="py-2 pr-4">Status</th>');
  if (c.rowAction) p('            <th className="py-2 pr-4"></th>');
  p('          </tr>');
  p('        </thead>');
  p('        <tbody>');
  p('          {visible.map((r) => (');
  if (c.highlight) {
    p('            <tr key={r.id} className={"border-b " + (isOverdue(r) ? "text-red-600" : "")}>');
  } else {
    p('            <tr key={r.id} className="border-b">');
  }
  p('              <td className="py-2 pr-4">{r.title}</td>');
  p('              <td className="py-2 pr-4">{r.owner}</td>');
  p('              <td className="py-2 pr-4">{r.due}</td>');
  p('              <td className="py-2 pr-4">{r.status}</td>');
  if (c.rowAction) {
    p('              <td className="py-2 pr-4">');
    p('                <button');
    p('                  onClick={() => toggle(r.id)}');
    p('                  className="rounded-md border px-2 py-1 text-xs hover:bg-muted"');
    p('                >');
    p('                  {r.status === "Done" ? "Reopen" : "Mark done"}');
    p('                </button>');
    p('              </td>');
  }
  p('            </tr>');
  p('          ))}');
  p('          {visible.length === 0 && (');
  p('            <tr>');
  p(`              <td colSpan={${c.rowAction ? 5 : 4}} className="py-6 text-center text-muted-foreground">`);
  p('                Nothing to show yet.');
  p('              </td>');
  p('            </tr>');
  p('          )}');
  p('        </tbody>');
  p('      </table>');
  p('    </div>');
  p('  )');
  p('}');
  p('');
  return L.join('\n');
}

function esc(s) {
  return String(s == null ? '' : s).replace(/[{}<>]/g, ' ').replace(/\s+/g, ' ').trim();
}
function oneLine(s) {
  return String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
}

// ---- router wiring ------------------------------------------------------------

// Best-effort: add `import Comp from "@/pages/<kebab>"` and a child route to the
// React-Router config in src/router.tsx. Idempotent and conservative — if the file
// doesn't match the known createBrowserRouter shape we leave it untouched and report
// wired:false (the screen file still exists; the maker can link it manually).
function wireRouter(srcDir, { componentName, route, kebab }) {
  const routerPath = path.join(srcDir, 'router.tsx');
  if (!fs.existsSync(routerPath)) return { wired: false, reason: 'no src/router.tsx' };
  let code = fs.readFileSync(routerPath, 'utf8');
  if (code.includes(`@/pages/${kebab}`) || new RegExp(`path:\\s*["']${route}["']`).test(code)) {
    return { wired: true, already: true };
  }
  if (!/createBrowserRouter\s*\(/.test(code) || !/children\s*:\s*\[/.test(code)) {
    return { wired: false, reason: 'router shape not recognized' };
  }
  // Insert the import after the last existing import line.
  const importLine = `import ${componentName} from "@/pages/${kebab}"`;
  const lines = code.split('\n');
  let lastImport = -1;
  for (let i = 0; i < lines.length; i += 1) if (/^\s*import\s/.test(lines[i])) lastImport = i;
  if (lastImport >= 0) lines.splice(lastImport + 1, 0, importLine);
  else lines.unshift(importLine);
  code = lines.join('\n');
  // Add the child route right after the first `children: [`.
  const childRoute = `{ path: "${route.replace(/^\//, '')}", element: <${componentName} /> }`;
  code = code.replace(/children\s*:\s*\[/, (m) => `${m}${childRoute}, `);
  fs.writeFileSync(routerPath, code);
  return { wired: true, already: false };
}

// ---- provider authoring (optional enhancement) --------------------------------

// Ask a provider to author the component; accept only if it looks like a real
// default-export TSX module. Any doubt → null (caller keeps the deterministic file).
async function aiAuthor(provider, task) {
  if (!provider || typeof provider.send !== 'function') return null;
  const caps = Object.entries(task.capabilities || {})
    .filter(([, v]) => v)
    .map(([k]) => k)
    .join(', ');
  const prompt = [
    'Write ONE self-contained React + TypeScript screen component.',
    'Hard rules:',
    '- Use ONLY `react` imports (useState/useMemo). No other imports, no UI libraries.',
    '- TypeScript strict, no unused variables, no `any`.',
    `- Default export named ${task.componentName}.`,
    '- Style with Tailwind className strings only.',
    '- Use inline sample data (no network).',
    `Build this screen: ${oneLine(task.goal)}`,
    caps ? `Capabilities to implement: ${caps}` : '',
    'Return ONLY the .tsx file contents — no markdown fences, no commentary.',
  ].join('\n');
  let text = '';
  try {
    const res = await provider.send({ prompt, timeoutMs: 60000 });
    text = (res && res.text) || '';
  } catch {
    return null;
  }
  return validateTsx(text, task.componentName);
}

// Accept the model's code only when it is plausibly a complete TSX module.
function validateTsx(text, componentName) {
  let code = String(text || '').trim();
  const fence = code.match(/```(?:tsx|ts|jsx|js)?\s*([\s\S]*?)```/);
  if (fence) code = fence[1].trim();
  if (!code) return null;
  const hasDefault = new RegExp(`export\\s+default\\s+function\\s+${componentName}\\b`).test(code) || /export\s+default\s+/.test(code);
  const importsReactOnly = !/^\s*import\s+.*from\s+["'](?!react["'])/m.test(code);
  const balanced = balancedBraces(code);
  const looksTsx = /return\s*\(/.test(code) && /</.test(code);
  if (hasDefault && importsReactOnly && balanced && looksTsx && code.length > 120) return code;
  return null;
}

function balancedBraces(code) {
  let b = 0;
  let par = 0;
  for (const ch of code) {
    if (ch === '{') b += 1;
    else if (ch === '}') b -= 1;
    else if (ch === '(') par += 1;
    else if (ch === ')') par -= 1;
    if (b < 0 || par < 0) return false;
  }
  return b === 0 && par === 0;
}

// ---- the build executor (code tasks) ------------------------------------------

// Author each code.screen task into the project and wire it up. `emit` is the loop's
// event sink; `provider` (optional) enhances the deterministic output. Returns one
// result per task with honest created/wired/source fields.
async function buildCodeTasks({ root, tasks, emit, rotation = 1, provider } = {}) {
  const srcDir = findSrc(root);
  fs.mkdirSync(path.join(srcDir, 'pages'), { recursive: true });
  const results = [];

  for (const task of tasks) {
    if (task.type !== 'code.screen') {
      results.push({ task: task.type, name: task.displayName || task.name, status: 'skipped', created: false, reason: 'not a code task' });
      continue;
    }
    // Never trust task.name as a path component — it can arrive from a client-supplied
    // intake payload. Slugify to a single safe segment and reject if nothing remains.
    const kebab = safeScreenName(task.name);
    if (!kebab) {
      results.push({ task: task.type, name: task.displayName || task.componentName || task.name, status: 'skipped', created: false, reason: 'invalid screen name' });
      continue;
    }
    const name = task.displayName || task.componentName;
    await emitSafe(emit, { rotation, stage: 3, agent: 'build-executor', level: 'info', message: `Authoring screen "${name}" in code` });

    // Deterministic baseline always exists; provider may upgrade it.
    let code = generateScreen(task);
    let source = 'deterministic';
    const ai = await aiAuthor(provider, task);
    if (ai) {
      code = ai;
      source = (provider && provider.id) || 'provider';
      await emitSafe(emit, { rotation, stage: 3, agent: 'build-executor', level: 'info', message: `AI authored "${name}" · validated as a real component` });
    }

    const pagesDir = path.join(srcDir, 'pages');
    const pagesPath = path.join(pagesDir, kebab + '.tsx');
    let created = false;
    if (!isWithin(pagesDir, pagesPath)) {
      results.push({ task: task.type, name, status: 'skipped', created: false, reason: 'invalid screen name' });
      continue;
    }
    try {
      fs.writeFileSync(pagesPath, code.endsWith('\n') ? code : code + '\n');
      created = true;
    } catch (e) {
      await emitSafe(emit, { rotation, stage: 3, agent: 'build-executor', level: 'bad', message: `Could not write the screen file: ${e.message}` });
      results.push({ task: task.type, name, status: 'failed', created: false, error: e.message });
      continue;
    }

    const wired = wireRouter(srcDir, { componentName: task.componentName, route: task.route, kebab });
    await emitSafe(emit, {
      rotation,
      stage: 3,
      agent: 'build-executor',
      level: 'good',
      message: wired.wired
        ? `Built "${name}" → src/pages/${kebab}.tsx · ${wired.already ? 'already routed' : 'added to your app’s routes at ' + task.route}`
        : `Built "${name}" → src/pages/${kebab}.tsx · couldn’t auto-route (${wired.reason}); link it from your menu`,
    });

    results.push({
      task: task.type,
      name,
      status: 'succeeded',
      created,
      file: path.relative(root, pagesPath).replace(/\\/g, '/'),
      route: task.route,
      wired: wired.wired,
      source,
    });
  }
  return results;
}

// ---- build verification (real test, no browser needed) ------------------------

// Run the project's own build (tsc + bundler) to verify the generated code compiles.
// This is a genuine pass/fail gate that needs no tenant and no browser. Skips cleanly
// when dependencies aren't installed (reported as not-verified, never a false green).
function verifyBuild(root, { timeoutMs = 240000 } = {}) {
  if (!fs.existsSync(path.join(root, 'node_modules'))) {
    return { ran: false, passed: false, reason: 'dependencies not installed (npm install first)' };
  }
  let script = null;
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    if (pkg.scripts && pkg.scripts.build) script = 'build';
  } catch {
    /* no package.json scripts */
  }
  const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const args = script ? ['run', script, '--silent'] : ['exec', '--', 'tsc', '--noEmit'];
  const res = spawnSync(npm, args, { cwd: root, encoding: 'utf8', timeout: timeoutMs, shell: process.platform === 'win32' });
  const out = `${res.stdout || ''}\n${res.stderr || ''}`;
  const passed = res.status === 0 && !res.error;
  const errors = passed ? [] : extractErrors(out);
  return { ran: true, passed, code: res.status, errors, output: out.slice(-4000) };
}

// Pull TypeScript/Vite error lines out of build output for a concise, real failure list.
function extractErrors(out) {
  const lines = String(out || '').split('\n');
  const errs = lines.filter((l) => /error TS\d+|ERROR|Could not resolve|is not assignable|Cannot find/i.test(l));
  return [...new Set(errs.map((l) => l.trim()))].slice(0, 12);
}

module.exports = { buildCodeTasks, verifyBuild, generateScreen, findSrc, isCodeApp, wireRouter, validateTsx };

async function emitSafe(emit, evt) {
  try {
    if (emit) await emit(evt);
  } catch {
    /* emit must never break a build */
  }
}
